# Exported from Render on 2026-05-07T12:18:33Z
version: "1"
projects:
- name: Bookwalker
  environments:
  - name: Production
    services:
    - type: web
      name: bookwalker-fontend
      runtime: docker
      repo: https://github.com/29121970t/bookwalker
      plan: free
      envVars:
      - key: PORT
        sync: true
        value: "80"
      - key: DB_HOSTNAME
        sync: true
      - key: DB_PORT
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_NAME
        sync: false
      - key: ADMIN_SEED_ENABLED
        sync: false
        value: "false"
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false

      region: frankfurt
      dockerContext: ./frontend
      dockerfilePath: ./frontend/Dockerfile
      autoDeployTrigger: "off"


    - type: web
      name: bookwalker-backend
      runtime: docker
      repo: https://github.com/29121970t/bookwalker
      plan: free
      envVars:
        - key: PORT
          sync: true
          value: "80"
        - key: BACKEND_URL
          sync: true
          value: "https://bookwalker-backend.onrender.com"
      
      region: frankfurt
      dockerContext: .
      dockerfilePath: ./Dockerfile

      autoDeployTrigger: "off"

      
databases:
  - name: bookwalker-db
    databaseName: bookwalker
    region: frankfurt
    plan: free
  

