spring.application.name=bookwalker

spring.datasource.url=jdbc:postgresql://localhost:5432/bookwalker
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.web=DEBUG


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true