name: CI/CD

on:
  push:
    branches:
      - main
jobs:
  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      PORT: ${ vars.PORT }
      BACKEND_URL: ${vars.BACKEND_URL}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
      - name: Install depenencies
        run: cd frontend && npm i
      - name: Test Build
        run: cd frontend &&  npm run build

  build_backend:
    name: Build Test & Scan Backend 
    runs-on: ubuntu-latest
    env:
      PORT: ${ vars.PORT }
      BACKEND_URL: ${vars.BACKEND_URL}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build
        run: ./mvnw clean verify

      

